id: P003310
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG02861
  title: ལམ་ཞུགས་ཀྱི་གང་ཟག་ལས་དང་པོ་པ་ལ་ཕན་པའི་བསྐྱེད་རྫོགས་ཀྱི་གནད་བསྡུས།
  author: ''
  volumes:
    982e34b0cd764ce9a33b7006c428eaf0:
      image_group_id: I1KG86200
      title: ''
      volume_number: 1
      total_pages: 214
      base_file: v001.txt
