id: IC05B1411
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T03:38:26+00:00'
last_modified: '2022-06-07T18:59:40.006321+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG02861
  title: ལམ་ཞུགས་ཀྱི་གང་ཟག་ལས་དང་པོ་པ་ལ་ཕན་པའི་བསྐྱེད་རྫོགས་ཀྱི་གནད་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    58A9:
      image_group_id: I1KG86200
      title: ''
      total_pages: 214
      order: 1
      base_file: 58A9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
